site_name: Lambda Forge

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
      primary: black


  
markdown_extensions:
  - pymdownx.tasklist  
  - pymdownx.emoji  
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
     