site_name: Lambda Forge

theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
    # - content.code.annotation
    - content.code.copy
  logo: images/logo.png
  favicon: images/logo.png
  palette:
      primary: black


  

# plugins:
#   - social
#   - search

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji

copyright: |
  &copy; 2024 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">Guilherme Pimenta</a>