site_name: Lambda Forge

theme:
  name: material
  palette:
    - scheme: slate
      primary: black


  
markdown_extensions:
  - pymdownx.tasklist  
  - pymdownx.emoji  
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
     