site_name: Lambda Forge

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    

nav:
  - Home: 
    - Introduction: index.md
    - Getting Started: home/page2.md
    - Creating a Hello World: home/page3.md
    - Securing Endpoints: home/page4.md
    - Lambda Layers: home/page5.md
    - Multi-Stage Environments: home/page6.md
    - Custom CodePipeline Steps: home/page7.md
    - Docs Generation: home/page8.md
    - Pre-Commit Hooks: home/page9.md
  - Example Projects:
    - Introduction: examples/page1.md
    - URL Shortener: examples/page2.md
    - CRUD Application: examples/page3.md
    - Image To QR Code: examples/page4.md
    - Authentication System: examples/page5.md
    - Real-Time Chat: examples/page6.md
    - Web Scraper: examples/page7.md
    - Telegram AI ChatBot: examples/page8.md
  - License: license/page1.md


markdown_extensions:
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tabbed

  - attr_list
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

copyright: |
  &copy; 2024 Guilherme Alves Pimenta

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/GuiPimenta-Dev"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/guilhermealvespimenta/"